contact/forms.py
from django import forms

class ContactForm(forms.Form):
    message = forms.CharField(label='Your Message', widget=forms.Textarea, error_messages={'required': 'Please enter a message.'})
    name = forms.CharField(label='First Name', widget=forms.TextInput, error_messages={'required': 'Please enter your name.'})
    email = forms.CharField(label='Email', widget=forms.TextInput, error_messages={'required': 'Please enter your email address.'})

contact/views.py
import datetime

from django.conf import settings
from django.contrib.sites.models import Site
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string

from contact.forms import ContactForm

def contactus(request):
    template_name = 'contact.html'

    context = {}
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
	    sender = form.cleaned_data['email']
            sender_name = form.cleaned_data['name']
	    message = form.cleaned_data['message']
            from django.core.mail import send_mail
            email_dict = { 'sender': sender, 'sender_name': sender_name, 'message': message, 'date': datetime.date.today() }
            subject = "Contact message sent from austincs.org"
            body = render_to_string('contact_notification.txt', email_dict)
            sent = send_mail(subject, body, settings.ADMINS[0][1], [settings.ADMINS[0][1]])
	    context['message'] = message
    else:
        form = ContactForm()

    context['form'] = form

    return render_to_response(template_name, context,
            context_instance=RequestContext(request))

contact/templates/contact.html
{% extends "home.html" %}

{% block page_title %}
    Contact
{% endblock %}

{% block content %}

  <div class="left half">
  <div class="container">
    <div class="row">
      <div class="span12">

    {% if message %}

      <div class="padded">
        <p>Your message has been sent:</p>
        <p>{{ message|linebreaks }}</p>
      </div>

    {% else %}

        <h2>Contact Us</h2>

        <form action="/contact/" method="post" class="form well" style="padding-bottom: 0;">
          <fieldset>

            <div class="control-group">
              {% csrf_token %}

              <p>
              <label class="control-label">Your Name<span class="required">* {{ form.name.errors }}</span></label>
              <input id="id_name" maxlength="200" name="name" type="text">
              </p>

              <p>
              <label class="control-label">Email Address<span class="required">* {{ form.email.errors }}</span></label>
              <input id="id_email" maxlength="200" name="email" type="text">
              </p>

              <p>
              <label class="control-label">Your Message<span class="required">* {{ form.message.errors }}</span></label>
              <textarea cols="40" id="id_message" name="message" rows="10"></textarea>
              </p>

              <button type="submit" class="btn btn-primary" name="submit" value="submit">Send</button>
            </div>

          </fieldset>
        </form>

    {% endif %}

      </div>
    </div>
  </div>

  </div>
  <div class="clear"></div>

{% endblock %}