developer/models.py
from django.db import models

AVAILABILITY_CHOICES = (
    ('A', 'Only one time during the school year'),
    ('B', 'Several times during the year'),
    ('C', 'Once a month'),
    ('D', 'Weekly'),
)

class Developer(models.Model):
    """
    Developers - Austin CSTA volunteer program sign-ups
    """
    name = models.CharField(max_length=200, blank=False)
    email = models.CharField(max_length=200, blank=False, unique=True,
            verbose_name='Email Address')
    bio = models.CharField(max_length=200, blank=False,
            help_text='What languages do you work in?  What are your areas of \
            programming expertise?')
    availability = models.CharField(max_length=1, blank=False,
            choices=AVAILABILITY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u"%s" % (self.name)

developer/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from developer.models import Developer

class DeveloperForm(forms.ModelForm):
    class Meta:
        model = Developer

    def __init__(self, *args, **kwargs):
        # self.user = kwargs.pop('user', None)
        super(DeveloperForm, self).__init__(*args, **kwargs)

developer/views.py
import datetime

from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string

from developer.models import Developer
from content.models import Description
from developer.forms import DeveloperForm

def developers(request):
    """
    """
    template_name = 'developer_signup.html'

    context = {}
    context["content"] = Description.objects.get(publish=True, slug='developers-austin-csta-volunteer-program-sign-ups')

    if request.method == 'POST':
        form = DeveloperForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context["thankyou"] = Description.objects.get(publish=True, slug='thank-you-for-signing-up')

            from django.core.mail import send_mail
            email_dict = { 'date': datetime.date.today() }  ## placeholder dict
            subject = "Austin CS Classrooms - Volunteer Confirmation"
            body = render_to_string('developer_notification.txt', email_dict)
            sent = send_mail(subject, body, settings.ADMINS[0][1], [settings.ADMINS[0][1]])

            return render_to_response("developer_signup_success.html", context,
                    context_instance=RequestContext(request))
        else:
            print form.is_valid()
            print form.errors
    else:
        form = DeveloperForm()

    context["form"] = form

    return render_to_response(template_name, context,
            context_instance=RequestContext(request))

developer/templates/developer_signup.html
{% extends "home.html" %}

{% block page_title %}
    Developer Sign-Up
{% endblock %}

{% block content %}

  {% include "title_body.html" %}

  <div class="right half">

  <div class="container">
    <div class="row">
      <div class="span12">

        <form action="/developers/" method="post" class="form well" style="padding-bottom: 0;">
          <fieldset>

            <div class="control-group">
              {% csrf_token %}

              <p>
              <label class="control-label">Name<span class="required">* {{ form.name.errors }}</span></label>
              <input id="id_name" maxlength="200" name="name" type="text">
              </p>

              <p>
              <label class="control-label">Email Address<span class="required">* {{ form.email.errors }}</span></label>
              <input id="id_email" maxlength="200" name="email" type="text">
              </p>

              <p>
              <label class="control-label">Bio<span class="required">* {{ form.bio.errors }}</span></label>
              <textarea class="field span12" id="id_bio" name="bio" rows="3" maxlength="200" placeholder="What languages do you work in?  What are your areas of programming expertise?"></textarea>
              </p>

              <p>
              <label class="control-label">Availability<span class="required">* {{ form.availability.errors }}</span></label>
              <select id="id_availability" name="availability">
                <option value="" selected="selected">------------</option>
                <option value="A">Only one time during the school year</option>
                <option value="B">Several times during the year</option>
                <option value="C">Once a month</option>
                <option value="D">Weekly</option>
              </select>
              </p>

              <button type="submit" class="btn btn-primary" name="submit" value="submit">Submit</button>
            </div>

          </fieldset>
        </form>

      </div>
    </div>
  </div>

  </div>
  <div class="clear"></div>

{% endblock %}

developer/templates/developer_signup_success.html
{% extends "home.html" %}

{% block page_title %}
    Developer Sign-Up
{% endblock %}

{% block content %}
  {% include "title_body.html" %}
  {% autoescape off %}{{ thankyou.body }}{% endautoescape %}
{% endblock %}