teacher/models.py
from django.db import models

class Needs(models.Model):
    description = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = "Needs"

    def __unicode__(self):
        return u"%s" % (self.description)

class Teacher(models.Model):
    name = models.CharField(max_length=200, blank=False)
    email = models.CharField(max_length=200, blank=False, unique=True,
            verbose_name='Email Address')
    school = models.CharField(max_length=200, blank=False,
            verbose_name='At which school do you teach?')
    school_zip_code = models.CharField(max_length=10, blank=False,
            verbose_name="What is the school's zip code? (for pairing purposes")
    grade_age = models.CharField(max_length=10, blank=False,
            verbose_name='What grade/age group do you teach?')
    no_of_students = models.CharField(max_length=4, blank=False,
            verbose_name='How many students?')
    needs = models.ManyToManyField(Needs, blank=False, help_text='What kinds of \
            participation from a member of the local programming community would \
            you like to see in your classroom?')
    other = models.CharField(max_length=200, blank=True, null=True, verbose_name='Other',
            help_text='Is there anything else we need to know about your class? \
            Any other comments?')
    created_at = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u"%s" % (self.name)

teacher/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from teacher.models import Teacher, Needs

class TeacherForm(forms.ModelForm):
    needs = forms.ModelMultipleChoiceField(queryset=Needs.objects.all(), required=False, widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Teacher

    def __init__(self, *args, **kwargs):
        # self.user = kwargs.pop('user', None)
        super(TeacherForm, self).__init__(*args, **kwargs)

teacher/views.py
import datetime

from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string

from teacher.models import Teacher, Needs
from content.models import Description
from teacher.forms import TeacherForm

def teachers(request):
    """
    """
    template_name = 'teacher_signup.html'

    context = {}
    context["content"] = Description.objects.get(publish=True, slug='central-texas-cs-teachers')

    if request.method == 'POST':
        form = TeacherForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context["thankyou"] = Description.objects.get(publish=True, slug='thank-you-for-signing-up')

            from django.core.mail import send_mail
            email_dict = { 'date': datetime.date.today() }  ## placeholder dict
            subject = "Austin CS Classrooms - Confirmation"
            body = render_to_string('teacher_notification.txt', email_dict)
            sent = send_mail(subject, body, settings.ADMINS[0][1], [settings.ADMINS[0][1]])

            return render_to_response("teacher_signup_success.html", context,
                    context_instance=RequestContext(request))
        else:
            print form.is_valid()
            print form.errors
    else:
        form = TeacherForm() #No post data

    context["form"] = form

    return render_to_response(template_name, context,
            context_instance=RequestContext(request))

teacher/templates/teacher_signup.html
{% extends "home.html" %}

{% block page_title %}
    Teacher Sign-Up
{% endblock %}

{% block content %}

  {% include "title_body.html" %}

  <div class="right half">

  <div class="container">
    <div class="row">
      <div class="span12">

        <form action="/teachers/" method="post" class="form well" style="padding-bottom: 0;">
          <fieldset>
            
            <div class="control-group">
              {% csrf_token %}
              
              <p>
              <label class="control-label">Name<span class="required">* {{ form.name.errors }}</span></label>
              <input id="id_name" maxlength="200" name="name" type="text">
              </p>

              <p>
              <label class="control-label">Email Address<span class="required">* {{ form.email.errors }}</span></label>
              <input id="id_email" maxlength="200" name="email" type="text">
              </p>

              <p>
              <label class="control-label">School<span class="required">* {{ form.school.errors }}</span></label>
              <input id="id_school" maxlength="200" name="school" type="text" placeholder="At which school do you teach?">
              </p>

              <p>
              <label class="control-label">School Zip Code<span class="required">* {{ form.school_zip_code.errors }}</span></label>
              <input id="id_school_zip_code" maxlength="200" name="school_zip_code" type="text" placeholder="(needed for pairing purposes)">
              </p>

              <p>
              <label class="control-label">Grade/Age Group<span class="required">* {{ form.grade_age.errors }}</span></label>
              <input id="id_grade_age" maxlength="10" name="grade_age" type="text" placeholder="What grade/age do you teach?">
              </p>

              <p>
              <label class="control-label">Students<span class="required">* {{ form.no_of_students.errors }}</span></label>
              <input id="id_no_of_students" maxlength="4" name="no_of_students" type="text" placeholder="How many students?">
              </p>

              <p>
              <label class="control-label">Needs<span class="required">* {{ form.needs.errors }}</span></label>
              {% for pk, need in form.needs.field.widget.choices %}
                <input type="checkbox" value="{{ pk }}" name="needs" /> {{ need }}<br />
              {% endfor %}
              </p>

              <p>
              <label class="control-label" for="multiSelect">Other</label>
              <textarea class="field span12" id="id_other" name="other" rows="3" maxlength="200" placeholder="Is there anything else we need to know about your class? Any other comments?"></textarea>
              </p>

              <button type="submit" class="btn btn-primary" name="submit" value="submit">Submit</button>
            </div>

          </fieldset>
        </form>

      </div>
    </div>
  </div>

  </div>
  <div class="clear"></div>

{% endblock %}

teacher/templates/teacher_signup_success.html
{% extends "home.html" %}

{% block page_title %}
    Teacher Sign-Up
{% endblock %}

{% block content %}
  {% include "title_body.html" %}
  {% autoescape off %}{{ thankyou.body }}{% endautoescape %}
{% endblock %}